name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Droplet via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html
            echo "Fetching leatest changes frm Github."
            git fetch origin 
            echo "Resetting to exact main branch state."
            git reset --hard origin/main
            echo "Restarting Apache"
            sudo systemctl restart apache2
            echo "Deployment complete!"
